### ISSUE TITLE
Cannot find module "meyda"

### ISSUE THREAD

**Issue by lazarljubenovic** [hughrawlinson/meyda#196]
Trying to `import` or `require` the module after installing (tried both `yarn` and `npm`) gives me `Cannot find module "meyda"`.

And indeed, the `package.json` for this module says `"main": "./dist/node/main.js"`, but there is no such folder. This is probably related to https://github.com/hughrawlinson/meyda/issues/112. I don't have a `dist` folder in my `node_modules/meyda`. Also, the [suggested unpkg link](https://unpkg.com/meyda@4.0.0/dist/web/meyda.min.js) confirms that the package isn't distributed with the `dist` folder (which is [suggested in the Wiki](https://github.com/hughrawlinson/meyda/wiki/getting-started#importing-meyda)).

**Comment by lazarljubenovic** [comment]
The current workaround is to navigate to the `node_modules/meyda`, and run `npm i && npm run build`. This makes everything work as expected.

**Comment by hughrawlinson** [comment]
Hey @lazarljubenovic - @2xAA and I will work on fixing this today :)

**Comment by hughrawlinson** [comment]
@lazarljubenovic this should be fixed in v4.0.1 which we've just published - could you check it out and confirm?

**Comment by lazarljubenovic** [comment]
Thanks for quick responses! Looks like it's getting there but still missing
some deeper deps.

```
Module not found: 'jsfft-for-meyda' in
/home/.../node_modules/meyda/dist/node
```

**Comment by hughrawlinson** [comment]
@lazarljubenovic could you try v4.0.2?

**Comment by lazarljubenovic** [comment]
```
Error in ./~/meyda/dist/node/main.js
Module not found: [CaseSensitivePathsPlugin] `/home/lazar/pi-proj/node_modules/meyda/node_modules/jsfft-for-meyda/dist/fft.js` does not match the corresponding path on disk - File does not exist.
```

:(

**Comment by hughrawlinson** [comment]
Can you share more about your webpack setup? `/node_modules/meyda/node_modules/jsfft-for-meyda` looks like the wrong path.

**Comment by hughrawlinson** [comment]
Also, can you try `rm -rf node_modules/meyda && npm install meyda`

**Comment by lazarljubenovic** [comment]
It's a `create-react-app` setup, so webpack is hidden away. 

And yup, I am nuking and re-installing the package again every time. Still no luck.

I think I'm onto something, though. The `meyda/dist/node/main.js` has the `require('jsfft-for-meyda')` which is probably why it's looking deeper into `node_modules`.

If I change my import to `import Meyda from 'meyda/dist/web/meyda.js'`, it _loads_, but logging `console.log(Meyda)` is an empty object, so I'm getting runtime errors like `_meyda2.default.createMeydaAnalyzer` is not a function. 

If I try `import * as Meyda from 'meyda/dist/web/meyda.js'` or its equivalent `const Meyda = require('meyda/dist/web/meyda.js')`, I get an object with the only property `default`, which is again an empty object.

**Comment by hughrawlinson** [comment]
> I think I'm onto something, though. The `meyda/dist/node/main.js has the `require('jsfft-for-meyda')` which is probably why it's looking deeper into `node_modules`.

This doesn't sound right - whichever implementation of require you have should be looking at the top level `node_modules`.

Could you check that meyda@4.0.2 is a dependency of your project?

Also, `meyda/dist/web/meyda.js` is for use in script tags, and exports a global `Meyda` object. For commonjs imports you should import `meyda/dist/node/main.js`. You can set this to happen automatically in your `webpack.config.js` as shown in [this commit](https://github.com/2xAA/modV/commit/80d75d28ea701fab08fdd4dc3d90c4dcaf4c0d36#diff-11e9f7f953edc64ba14b0cc350ae7b9d)

**Comment by lazarljubenovic** [comment]
Interesting. I was deleting just `meyda` from `node_modules` (either with `npm` command or with `rm -rf`) and re-installing, but the issue remained. When I nuked the whole `node_modules`, I got it to work. I have to import from `mayda/dist/node/main.js` explicitly now though, but I don't mind it.

I don't have access to `webpack.config.js`, as I don't want to `eject` the `create-react-app` (it hides away the build process, and I don't want to fiddle with it).

So as far as I'm concerned, this is solved (since you provided the webpack configuration thing for people who have access to it). :ok_hand: 

Now on to figuring out how to extract features! :dancer:

**Comment by hughrawlinson** [comment]
Great, thanks for helping us figure this out! I'll close this issue as you say it's solved, but I'll open another issue to track the require via browser property. It seems that webpack expects the file in package.json/browser to be a commonjs module, which is weird to me, but if more people report this, we'll take that to be the correct behaviour.

Enjoy the feature extracting, please let us know when you've built something cool!

**Comment by erezsh** [comment]
I'm still getting this error through the client. Here's what I did:

    $ sudo npm install -g meyda
    $ meyda a b

    module.js:557
        throw err;
        ^

    Error: Cannot find module '../dist/node/main.js'
        at Function.Module._resolveFilename (module.js:555:15)
        at Function.Module._load (module.js:482:25)
        at Module.require (module.js:604:17)
        at require (internal/module.js:11:18)
        at /usr/lib/node_modules/meyda/bin/cli.js:27:15
        at Object.<anonymous> (/usr/lib/node_modules/meyda/bin/cli.js:222:3)
        at Module._compile (module.js:660:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
        at tryModuleLoad (module.js:513:12)



    $ node --version
    v9.3.0
    $ npm --version
    5.5.1

**Comment by jakubfiala** [comment]
@erezsh this is actually related to #225 (a npm deployment issue) and I'd really like to fix it but I don't currently have permissions for the meyda npm account. paging @meyda/owners in case anyone has 10 min to look into it?

**Comment by hughrawlinson** [comment]
@jakubfiala gave you permission now, not sure why you didn't have it before. Sorry! I think maybe you didn't have an npm account at the time? Not sure.

**Comment by jakubfiala** [comment]
thanks @hughrawlinson! hmm weird, i definitely did have an npm account

**Comment by jakubfiala** [comment]
@erezsh @hughrawlinson this should now be fixed and published as `4.1.3` 🎉

The issue was that the 'empty npmignore' trick didn't work, i.e. npm was falling back to gitignore when publishing, but not when running `npm pack`. We obviously want to gitignore `/dist` but we don't want to npmignore it, so I had to add `!dist` to npmignore, which fixed the issue.

Sorry about this period of inconvenience and hope you all enjoy the new features!

**Comment by rumschuettel** [comment]
Thanks! It can now be require'd right from a standard `npm install meyda`, awesome.
